### ISSUE TITLE
issue line 170 in bit_array.c 

### ISSUE THREAD

**Issue by longscu** [noporpoise/BitArray#10]
Hi, 

It seems that there is an issue in the function

    static word_t __inline windows_popcount(word_t w)
    {
      w = w - ((w >> 1) & (word_t)~(word_t)0/3);
      w = (w & (word_t)~(word_t)0/15_3) + ((w >> 2) & (word_t)~(word_t)0/15_3);
      w = (w + (w >> 4)) & (word_t)~(word_t)0/255*15;
      c = (word_t)(w \* ((word_t)~(word_t)0/255)) >> (sizeof(word_t) - 1) \* 8;
    }

line 170 in bit_array.c

Best Regards,
Long Yuan

**Comment by noporpoise** [comment]
Sorry I missed this issue. I'm not clear what the issue is - could you explain?
